import type { Edge, Node } from 'reactflow';

// Workflow template interface
export interface WorkflowTemplate {
  id: string;
  name: string;
  description: string;
  nodes: Node[];
  edges: Edge[];
  category: 'fundraising' | 'support' | 'survey' | 'sales' | 'appointment' | 'custom';
}

// Workflow templates
export const workflowTemplates: WorkflowTemplate[] = [
  {
    id: 'fundraising-basic',
    name: 'Basic Fundraising',
    description: 'Standard fundraising workflow with donation processing',
    category: 'fundraising',
    nodes: [
      {
        id: '1',
        type: 'start',
        position: { x: 400, y: 0 },
        data: { label: 'Start Call' },
      },
      {
        id: '2',
        type: 'decision',
        position: { x: 400, y: 150 },
        data: {
          label: 'Donor Picks Up?',
          options: ['Yes', 'No'],
          description: 'Check if donor answers the call',
        },
      },
      {
        id: '3',
        type: 'action',
        position: { x: 100, y: 300 },
        data: {
          label: 'Leave Voicemail',
          description: 'Leave a brief voicemail with callback number',
          action: 'voicemail',
        },
      },
      {
        id: '4',
        type: 'action',
        position: { x: 700, y: 300 },
        data: {
          label: 'Begin Conversation',
          description: 'Start the fundraising conversation',
          action: 'conversation',
        },
      },
      {
        id: '5',
        type: 'decision',
        position: { x: 700, y: 450 },
        data: {
          label: 'Donor Interested?',
          options: ['Yes', 'No'],
          description: 'Assess donor interest level',
        },
      },
      {
        id: '6',
        type: 'action',
        position: { x: 900, y: 600 },
        data: {
          label: 'Process Donation',
          description: 'Confirm donation and process payment',
          action: 'donation',
        },
      },
      {
        id: '7',
        type: 'action',
        position: { x: 500, y: 600 },
        data: {
          label: 'Thank & End Call',
          description: 'Thank donor and end call gracefully',
          action: 'end_call',
        },
      },
      {
        id: '3-end',
        type: 'end',
        position: { x: 100, y: 450 },
        data: { label: 'End Workflow' },
      },
      {
        id: '8',
        type: 'end',
        position: { x: 700, y: 750 },
        data: { label: 'End Workflow' },
      },
    ],
    edges: [
      {
        id: 'e1-2',
        source: '1',
        target: '2',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e2-3',
        source: '2',
        target: '3',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e2-4',
        source: '2',
        target: '4',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e3-end',
        source: '3',
        target: '3-end',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e4-5',
        source: '4',
        target: '5',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e5-7',
        source: '5',
        target: '7',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e5-6',
        source: '5',
        target: '6',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e6-8',
        source: '6',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e7-8',
        source: '7',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
    ],
  },
  {
    id: 'support-basic',
    name: 'Customer Support',
    description: 'Basic customer support workflow with issue resolution',
    category: 'support',
    nodes: [
      {
        id: '1',
        type: 'start',
        position: { x: 400, y: 0 },
        data: { label: 'Start Support Call' },
      },
      {
        id: '2',
        type: 'decision',
        position: { x: 400, y: 150 },
        data: {
          label: 'Customer Available?',
          options: ['Yes', 'No'],
          description: 'Check if customer answers',
        },
      },
      {
        id: '3',
        type: 'action',
        position: { x: 100, y: 300 },
        data: {
          label: 'Leave Message',
          description: 'Leave support callback message',
          action: 'voicemail',
        },
      },
      {
        id: '4',
        type: 'action',
        position: { x: 700, y: 300 },
        data: {
          label: 'Greet Customer',
          description: 'Welcome and identify customer',
          action: 'conversation',
        },
      },
      {
        id: '5',
        type: 'decision',
        position: { x: 700, y: 450 },
        data: {
          label: 'Issue Resolved?',
          options: ['Yes', 'No'],
          description: 'Check if issue is resolved',
        },
      },
      {
        id: '7',
        type: 'action',
        position: { x: 500, y: 600 },
        data: {
          label: 'Confirm Resolution',
          description: 'Confirm issue resolution and end call',
          action: 'end_call',
        },
      },
      {
        id: '6',
        type: 'action',
        position: { x: 900, y: 600 },
        data: {
          label: 'Escalate Issue',
          description: 'Transfer to senior support',
          action: 'conversation',
        },
      },
      {
        id: '3-end',
        type: 'end',
        position: { x: 100, y: 450 },
        data: { label: 'End Support Call' },
      },
      {
        id: '8',
        type: 'end',
        position: { x: 700, y: 750 },
        data: { label: 'End Support Call' },
      },
    ],
    edges: [
      {
        id: 'e1-2',
        source: '1',
        target: '2',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e2-3',
        source: '2',
        target: '3',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e2-4',
        source: '2',
        target: '4',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e3-end',
        source: '3',
        target: '3-end',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e4-5',
        source: '4',
        target: '5',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e5-7',
        source: '5',
        target: '7',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e5-6',
        source: '5',
        target: '6',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e6-8',
        source: '6',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e7-8',
        source: '7',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
    ],
  },
  {
    id: 'survey-basic',
    name: 'Survey Collection',
    description: 'Simple survey workflow for data collection',
    category: 'survey',
    nodes: [
      {
        id: '1',
        type: 'start',
        position: { x: 400, y: 0 },
        data: { label: 'Start Survey' },
      },
      {
        id: '2',
        type: 'decision',
        position: { x: 400, y: 150 },
        data: {
          label: 'Person Available?',
          options: ['Yes', 'No'],
          description: 'Check if person answers',
        },
      },
      {
        id: '3',
        type: 'action',
        position: { x: 100, y: 300 },
        data: {
          label: 'End Call',
          description: 'End call if no one available',
          action: 'end_call',
        },
      },
      {
        id: '4',
        type: 'action',
        position: { x: 700, y: 300 },
        data: {
          label: 'Conduct Survey',
          description: 'Ask survey questions',
          action: 'conversation',
        },
      },
      {
        id: '5',
        type: 'decision',
        position: { x: 700, y: 450 },
        data: {
          label: 'Survey Complete?',
          options: ['Yes', 'No'],
          description: 'Check if survey is finished',
        },
      },
      {
        id: '7',
        type: 'action',
        position: { x: 500, y: 600 },
        data: {
          label: 'Continue Survey',
          description: 'Continue with remaining questions',
          action: 'conversation',
        },
      },
      {
        id: '6',
        type: 'action',
        position: { x: 900, y: 600 },
        data: {
          label: 'Thank & End',
          description: 'Thank participant and end call',
          action: 'end_call',
        },
      },
      {
        id: '3-end',
        type: 'end',
        position: { x: 100, y: 450 },
        data: { label: 'End Survey' },
      },
      {
        id: '7-loop',
        type: 'end',
        position: { x: 500, y: 750 },
        data: { label: 'Return to Survey' },
      },
      {
        id: '8',
        type: 'end',
        position: { x: 900, y: 750 },
        data: { label: 'End Survey' },
      },
    ],
    edges: [
      {
        id: 'e1-2',
        source: '1',
        target: '2',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e2-3',
        source: '2',
        target: '3',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e2-4',
        source: '2',
        target: '4',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e3-end',
        source: '3',
        target: '3-end',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e4-5',
        source: '4',
        target: '5',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e5-7',
        source: '5',
        target: '7',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e5-6',
        source: '5',
        target: '6',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e7-4',
        source: '7',
        target: '4',
        label: 'Loop',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#f59e0b', strokeWidth: 2 },
      },
      {
        id: 'e6-8',
        source: '6',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
    ],
  },
  {
    id: 'fundraising-major-gifts',
    name: 'Major Gifts Outreach',
    description: 'High-value donor engagement with personalized approach',
    category: 'fundraising',
    nodes: [
      {
        id: '1',
        type: 'start',
        position: { x: 400, y: 0 },
        data: { label: 'Start Call' },
      },
      {
        id: '2',
        type: 'decision',
        position: { x: 400, y: 150 },
        data: {
          label: 'Donor Available?',
          options: ['Yes', 'No'],
          description: 'Check if high-value donor answers',
        },
      },
      {
        id: '3',
        type: 'action',
        position: { x: 100, y: 300 },
        data: {
          label: 'Schedule Callback',
          description: 'Arrange personalized follow-up',
          action: 'voicemail',
        },
      },
      {
        id: '4',
        type: 'action',
        position: { x: 700, y: 300 },
        data: {
          label: 'Build Relationship',
          description: 'Personalized conversation about impact',
          action: 'conversation',
        },
      },
      {
        id: '5',
        type: 'decision',
        position: { x: 700, y: 450 },
        data: {
          label: 'Ready to Commit?',
          options: ['Yes', 'No', 'Maybe'],
          description: 'Assess commitment level',
        },
      },
      {
        id: '6',
        type: 'action',
        position: { x: 500, y: 600 },
        data: {
          label: 'Schedule Meeting',
          description: 'Arrange in-person or video meeting',
          action: 'conversation',
        },
      },
      {
        id: '7',
        type: 'action',
        position: { x: 900, y: 600 },
        data: {
          label: 'Process Major Gift',
          description: 'Handle large donation with care',
          action: 'donation',
        },
      },
      {
        id: '3-end',
        type: 'end',
        position: { x: 100, y: 450 },
        data: { label: 'End Workflow' },
      },
      {
        id: '8',
        type: 'end',
        position: { x: 700, y: 750 },
        data: { label: 'End Workflow' },
      },
    ],
    edges: [
      {
        id: 'e1-2',
        source: '1',
        target: '2',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e2-3',
        source: '2',
        target: '3',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e2-4',
        source: '2',
        target: '4',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e3-end',
        source: '3',
        target: '3-end',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e4-5',
        source: '4',
        target: '5',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e5-6',
        source: '5',
        target: '6',
        label: 'Maybe',
        type: 'smoothstep',
        style: { stroke: '#f59e0b', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e5-7',
        source: '5',
        target: '7',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e6-8',
        source: '6',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e7-8',
        source: '7',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
    ],
  },
  {
    id: 'fundraising-event',
    name: 'Event Registration',
    description: 'Promote fundraising event and register attendees',
    category: 'fundraising',
    nodes: [
      {
        id: '1',
        type: 'start',
        position: { x: 400, y: 0 },
        data: { label: 'Start Call' },
      },
      {
        id: '2',
        type: 'decision',
        position: { x: 400, y: 150 },
        data: {
          label: 'Contact Reached?',
          options: ['Yes', 'No'],
          description: 'Check if contact answers',
        },
      },
      {
        id: '3',
        type: 'action',
        position: { x: 100, y: 300 },
        data: {
          label: 'Leave Event Info',
          description: 'Voicemail with event details',
          action: 'voicemail',
        },
      },
      {
        id: '4',
        type: 'action',
        position: { x: 700, y: 300 },
        data: {
          label: 'Introduce Event',
          description: 'Share event purpose and details',
          action: 'conversation',
        },
      },
      {
        id: '5',
        type: 'decision',
        position: { x: 700, y: 450 },
        data: {
          label: 'Will Attend?',
          options: ['Yes', 'No'],
          description: 'Check attendance interest',
        },
      },
      {
        id: '6',
        type: 'action',
        position: { x: 900, y: 600 },
        data: {
          label: 'Register Attendee',
          description: 'Complete registration and send confirmation',
          action: 'conversation',
        },
      },
      {
        id: '7',
        type: 'action',
        position: { x: 500, y: 600 },
        data: {
          label: 'Send More Info',
          description: 'Provide additional event materials',
          action: 'end_call',
        },
      },
      {
        id: '3-end',
        type: 'end',
        position: { x: 100, y: 450 },
        data: { label: 'End Workflow' },
      },
      {
        id: '8',
        type: 'end',
        position: { x: 700, y: 750 },
        data: { label: 'End Workflow' },
      },
    ],
    edges: [
      {
        id: 'e1-2',
        source: '1',
        target: '2',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e2-3',
        source: '2',
        target: '3',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e2-4',
        source: '2',
        target: '4',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e3-end',
        source: '3',
        target: '3-end',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e4-5',
        source: '4',
        target: '5',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e5-7',
        source: '5',
        target: '7',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e5-6',
        source: '5',
        target: '6',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e6-8',
        source: '6',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e7-8',
        source: '7',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
    ],
  },
  {
    id: 'sales-qualification',
    name: 'Lead Qualification',
    description: 'Qualify sales leads and schedule demos',
    category: 'sales',
    nodes: [
      {
        id: '1',
        type: 'start',
        position: { x: 400, y: 0 },
        data: { label: 'Start Call' },
      },
      {
        id: '2',
        type: 'decision',
        position: { x: 400, y: 150 },
        data: {
          label: 'Lead Answers?',
          options: ['Yes', 'No'],
          description: 'Check if lead is available',
        },
      },
      {
        id: '3',
        type: 'action',
        position: { x: 100, y: 300 },
        data: {
          label: 'Leave Voicemail',
          description: 'Brief intro with callback request',
          action: 'voicemail',
        },
      },
      {
        id: '4',
        type: 'action',
        position: { x: 700, y: 300 },
        data: {
          label: 'Qualify Lead',
          description: 'Ask qualifying questions',
          action: 'conversation',
        },
      },
      {
        id: '5',
        type: 'decision',
        position: { x: 700, y: 450 },
        data: {
          label: 'Qualified Lead?',
          options: ['Yes', 'No'],
          description: 'Assess fit and interest',
        },
      },
      {
        id: '6',
        type: 'action',
        position: { x: 900, y: 600 },
        data: {
          label: 'Schedule Demo',
          description: 'Book product demonstration',
          action: 'conversation',
        },
      },
      {
        id: '7',
        type: 'action',
        position: { x: 500, y: 600 },
        data: {
          label: 'Send Resources',
          description: 'Provide educational materials',
          action: 'end_call',
        },
      },
      {
        id: '3-end',
        type: 'end',
        position: { x: 100, y: 450 },
        data: { label: 'End Workflow' },
      },
      {
        id: '8',
        type: 'end',
        position: { x: 700, y: 750 },
        data: { label: 'End Workflow' },
      },
    ],
    edges: [
      {
        id: 'e1-2',
        source: '1',
        target: '2',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e2-3',
        source: '2',
        target: '3',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e2-4',
        source: '2',
        target: '4',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e3-end',
        source: '3',
        target: '3-end',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e4-5',
        source: '4',
        target: '5',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e5-7',
        source: '5',
        target: '7',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e5-6',
        source: '5',
        target: '6',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e6-8',
        source: '6',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e7-8',
        source: '7',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
    ],
  },
  {
    id: 'appointment-reminder',
    name: 'Appointment Reminder',
    description: 'Confirm appointments and handle rescheduling',
    category: 'appointment',
    nodes: [
      {
        id: '1',
        type: 'start',
        position: { x: 400, y: 0 },
        data: { label: 'Start Call' },
      },
      {
        id: '2',
        type: 'decision',
        position: { x: 400, y: 150 },
        data: {
          label: 'Contact Reached?',
          options: ['Yes', 'No'],
          description: 'Check if person answers',
        },
      },
      {
        id: '3',
        type: 'action',
        position: { x: 100, y: 300 },
        data: {
          label: 'Leave Reminder',
          description: 'Voicemail with appointment details',
          action: 'voicemail',
        },
      },
      {
        id: '4',
        type: 'action',
        position: { x: 700, y: 300 },
        data: {
          label: 'Confirm Appointment',
          description: 'Verify appointment details',
          action: 'conversation',
        },
      },
      {
        id: '5',
        type: 'decision',
        position: { x: 700, y: 450 },
        data: {
          label: 'Can Attend?',
          options: ['Yes', 'No'],
          description: 'Check if they can make it',
        },
      },
      {
        id: '6',
        type: 'action',
        position: { x: 900, y: 600 },
        data: {
          label: 'Confirm & Send Reminder',
          description: 'Send confirmation and details',
          action: 'end_call',
        },
      },
      {
        id: '7',
        type: 'action',
        position: { x: 500, y: 600 },
        data: {
          label: 'Reschedule',
          description: 'Find new appointment time',
          action: 'conversation',
        },
      },
      {
        id: '3-end',
        type: 'end',
        position: { x: 100, y: 450 },
        data: { label: 'End Workflow' },
      },
      {
        id: '8',
        type: 'end',
        position: { x: 700, y: 750 },
        data: { label: 'End Workflow' },
      },
    ],
    edges: [
      {
        id: 'e1-2',
        source: '1',
        target: '2',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e2-3',
        source: '2',
        target: '3',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e2-4',
        source: '2',
        target: '4',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e3-end',
        source: '3',
        target: '3-end',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e4-5',
        source: '4',
        target: '5',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e5-7',
        source: '5',
        target: '7',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e5-6',
        source: '5',
        target: '6',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e6-8',
        source: '6',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e7-8',
        source: '7',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
    ],
  },
  {
    id: 'survey-satisfaction',
    name: 'Satisfaction Survey',
    description: 'Measure customer satisfaction with rating system',
    category: 'survey',
    nodes: [
      {
        id: '1',
        type: 'start',
        position: { x: 400, y: 0 },
        data: { label: 'Start Survey' },
      },
      {
        id: '2',
        type: 'decision',
        position: { x: 400, y: 150 },
        data: {
          label: 'Customer Available?',
          options: ['Yes', 'No'],
          description: 'Check if customer answers',
        },
      },
      {
        id: '3',
        type: 'action',
        position: { x: 100, y: 300 },
        data: {
          label: 'End Call',
          description: 'No survey if unavailable',
          action: 'end_call',
        },
      },
      {
        id: '4',
        type: 'action',
        position: { x: 700, y: 300 },
        data: {
          label: 'Ask Satisfaction Rating',
          description: 'Request 1-10 satisfaction score',
          action: 'conversation',
        },
      },
      {
        id: '5',
        type: 'decision',
        position: { x: 700, y: 450 },
        data: {
          label: 'Rating High?',
          options: ['High (8-10)', 'Medium (5-7)', 'Low (1-4)'],
          description: 'Categorize satisfaction level',
        },
      },
      {
        id: '6',
        type: 'action',
        position: { x: 300, y: 600 },
        data: {
          label: 'Ask for Improvement',
          description: 'Collect feedback on issues',
          action: 'conversation',
        },
      },
      {
        id: '7',
        type: 'action',
        position: { x: 700, y: 600 },
        data: {
          label: 'Thank Customer',
          description: 'Express gratitude for feedback',
          action: 'conversation',
        },
      },
      {
        id: '8',
        type: 'action',
        position: { x: 1100, y: 600 },
        data: {
          label: 'Request Testimonial',
          description: 'Ask for review or referral',
          action: 'conversation',
        },
      },
      {
        id: '3-end',
        type: 'end',
        position: { x: 100, y: 450 },
        data: { label: 'End Survey' },
      },
      {
        id: '9',
        type: 'end',
        position: { x: 700, y: 750 },
        data: { label: 'End Survey' },
      },
    ],
    edges: [
      {
        id: 'e1-2',
        source: '1',
        target: '2',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e2-3',
        source: '2',
        target: '3',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e2-4',
        source: '2',
        target: '4',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e3-end',
        source: '3',
        target: '3-end',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e4-5',
        source: '4',
        target: '5',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e5-6',
        source: '5',
        target: '6',
        label: 'Low',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e5-7',
        source: '5',
        target: '7',
        label: 'Medium',
        type: 'smoothstep',
        style: { stroke: '#f59e0b', strokeWidth: 2 },
      },
      {
        id: 'e5-8',
        source: '5',
        target: '8',
        label: 'High',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e6-9',
        source: '6',
        target: '9',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e7-9',
        source: '7',
        target: '9',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e8-9',
        source: '8',
        target: '9',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
    ],
  },
  {
    id: 'support-technical',
    name: 'Technical Support',
    description: 'Troubleshoot technical issues with escalation path',
    category: 'support',
    nodes: [
      {
        id: '1',
        type: 'start',
        position: { x: 400, y: 0 },
        data: { label: 'Start Support Call' },
      },
      {
        id: '2',
        type: 'decision',
        position: { x: 400, y: 150 },
        data: {
          label: 'Customer Available?',
          options: ['Yes', 'No'],
          description: 'Check if customer answers',
        },
      },
      {
        id: '3',
        type: 'action',
        position: { x: 100, y: 300 },
        data: {
          label: 'Leave Support Message',
          description: 'Provide support ticket number',
          action: 'voicemail',
        },
      },
      {
        id: '4',
        type: 'action',
        position: { x: 700, y: 300 },
        data: {
          label: 'Identify Issue',
          description: 'Gather problem details',
          action: 'conversation',
        },
      },
      {
        id: '5',
        type: 'decision',
        position: { x: 700, y: 450 },
        data: {
          label: 'Issue Complexity?',
          options: ['Simple', 'Complex'],
          description: 'Assess technical difficulty',
        },
      },
      {
        id: '6',
        type: 'action',
        position: { x: 500, y: 600 },
        data: {
          label: 'Provide Solution',
          description: 'Walk through troubleshooting steps',
          action: 'conversation',
        },
      },
      {
        id: '7',
        type: 'action',
        position: { x: 900, y: 600 },
        data: {
          label: 'Escalate to Specialist',
          description: 'Transfer to technical expert',
          action: 'conversation',
        },
      },
      {
        id: '3-end',
        type: 'end',
        position: { x: 100, y: 450 },
        data: { label: 'End Support Call' },
      },
      {
        id: '8',
        type: 'end',
        position: { x: 700, y: 750 },
        data: { label: 'End Support Call' },
      },
    ],
    edges: [
      {
        id: 'e1-2',
        source: '1',
        target: '2',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e2-3',
        source: '2',
        target: '3',
        label: 'No',
        type: 'smoothstep',
        style: { stroke: '#ef4444', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e2-4',
        source: '2',
        target: '4',
        label: 'Yes',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e3-end',
        source: '3',
        target: '3-end',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e4-5',
        source: '4',
        target: '5',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e5-6',
        source: '5',
        target: '6',
        label: 'Simple',
        type: 'smoothstep',
        style: { stroke: '#10b981', strokeWidth: 2 },
        sourceHandle: 'left',
      },
      {
        id: 'e5-7',
        source: '5',
        target: '7',
        label: 'Complex',
        type: 'smoothstep',
        style: { stroke: '#f59e0b', strokeWidth: 2 },
        sourceHandle: 'right',
      },
      {
        id: 'e6-8',
        source: '6',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
      {
        id: 'e7-8',
        source: '7',
        target: '8',
        type: 'smoothstep',
        animated: true,
        style: { stroke: '#3b82f6', strokeWidth: 2 },
      },
    ],
  },
];
